#!/usr/bin/env python3
"""Generate PNG icons for cocktail machine UI (320x480 ILI9488).

Downloads SVG icons from Font Awesome 6 (CC BY 4.0, free),
converts to PNG with custom colors using cairosvg + Pillow.

Requires: pip install Pillow cairosvg
Output:   firmware/data/*.png
"""

import os
import re
import io
import random
import struct
from urllib.request import urlopen
from PIL import Image, ImageDraw, ImageFont, ImageChops
import cairosvg

OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")
os.makedirs(OUT_DIR, exist_ok=True)

# ── Theme colors (generated by theme.sh) ──
from theme_colors import *

BG_ACCENT_DIM = tuple(max(0, c * 2 // 3) for c in BG_ACCENT)  # ~66% brightness
AMBER = PEACH  # alias

# ── Font Awesome 6 solid SVGs (GitHub raw) ──
FA_BASE = "https://raw.githubusercontent.com/FortAwesome/Font-Awesome/6.x/svgs/solid"
FA_ICONS = {
    "martini-glass":        f"{FA_BASE}/martini-glass.svg",
    "martini-glass-citrus": f"{FA_BASE}/martini-glass-citrus.svg",
    "circle-check":         f"{FA_BASE}/circle-check.svg",
    "triangle-exclamation": f"{FA_BASE}/triangle-exclamation.svg",
    "wine-glass":           f"{FA_BASE}/wine-glass.svg",
    "wine-glass-empty":     f"{FA_BASE}/wine-glass-empty.svg",
    "champagne-glasses":    f"{FA_BASE}/champagne-glasses.svg",
    "lemon":                f"{FA_BASE}/lemon.svg",
    "whiskey-glass":        f"{FA_BASE}/whiskey-glass.svg",
    "beer-mug-empty":       f"{FA_BASE}/beer-mug-empty.svg",
    "bottle-droplet":       f"{FA_BASE}/bottle-droplet.svg",
    "star":                 f"{FA_BASE}/star.svg",
}

# Icons used for background tile pattern
BG_PATTERN_ICONS = [
    "martini-glass", "wine-glass", "champagne-glasses",
    "lemon", "whiskey-glass", "beer-mug-empty",
    "bottle-droplet", "star",
]

_svg_cache: dict[str, bytes] = {}


def fetch_svg(name: str) -> bytes:
    """Download and cache an SVG from Font Awesome."""
    if name not in _svg_cache:
        url = FA_ICONS[name]
        print(f"  Downloading {name}.svg ...")
        _svg_cache[name] = urlopen(url).read()
    return _svg_cache[name]


def svg_to_png(svg_data: bytes, width: int, height: int) -> Image.Image:
    """Render SVG to RGBA PIL Image at given size."""
    png_bytes = cairosvg.svg2png(
        bytestring=svg_data,
        output_width=width,
        output_height=height,
    )
    return Image.open(io.BytesIO(png_bytes)).convert("RGBA")


def colorize(img: Image.Image, color: tuple[int, int, int]) -> Image.Image:
    """Recolor icon to given color, preserving alpha."""
    r, g, b = color
    pixels = img.load()
    w, h = img.size
    for y in range(h):
        for x in range(w):
            _, _, _, a = pixels[x, y]
            if a > 0:
                pixels[x, y] = (r, g, b, a)
    return img


def flatten_alpha(img: Image.Image, threshold: int = 100) -> Image.Image:
    """Threshold alpha to 0 or 255 — MUST be the last step before save.

    Needed for displays without MISO (ILI9488 write-only SPI)
    that can't read-back pixels for alpha blending.
    """
    pixels = img.load()
    w, h = img.size
    for y in range(h):
        for x in range(w):
            r, g, b, a = pixels[x, y]
            pixels[x, y] = (r, g, b, 255) if a > threshold else (0, 0, 0, 0)
    return img


def fit_icon(img: Image.Image, target_w: int, target_h: int) -> Image.Image:
    """Fit icon into target box preserving aspect ratio, center on transparent."""
    img.thumbnail((target_w, target_h), Image.LANCZOS)
    result = Image.new("RGBA", (target_w, target_h), (0, 0, 0, 0))
    offset_x = (target_w - img.width) // 2
    offset_y = (target_h - img.height) // 2
    result.paste(img, (offset_x, offset_y), img)
    return result


def save(img: Image.Image, name: str):
    path = os.path.join(OUT_DIR, name)
    img.save(path, "PNG", optimize=True)
    sz = os.path.getsize(path)
    print(f"  {name:16s} {img.width}x{img.height}  {sz:>6,d} bytes")


# ═══════════════════════════════════════
# 1. bg.png — gradient + tiled icons (Telegram-style)
# ═══════════════════════════════════════
ICON_SIZE = 24          # px per icon in pattern
GRID_STEP = 52          # spacing between icon centers
ICON_ALPHA = 90         # opacity (0-255), clearly visible
PATTERN_SEED = 42       # reproducible layout

def gen_bg():
    W, H = 320, 480

    # Step 1: gradient
    img = Image.new("RGBA", (W, H))
    draw = ImageDraw.Draw(img)
    for y in range(H):
        t = y / (H - 1)
        r = int(BG_TOP[0] + (BG_BOT[0] - BG_TOP[0]) * t)
        g = int(BG_TOP[1] + (BG_BOT[1] - BG_TOP[1]) * t)
        b = int(BG_TOP[2] + (BG_BOT[2] - BG_TOP[2]) * t)
        draw.line([(0, y), (W - 1, y)], fill=(r, g, b, 255))

    # Step 2: pre-render pattern icons (small, white, various rotations)
    print("  Preparing background pattern icons...")
    icon_stamps = []
    for name in BG_PATTERN_ICONS:
        svg = fetch_svg(name)
        base = svg_to_png(svg, ICON_SIZE * 3, ICON_SIZE * 3)
        base = colorize(base, BG_ACCENT_DIM)
        base.thumbnail((ICON_SIZE, ICON_SIZE), Image.LANCZOS)
        # pre-generate 4 rotations (0, 10, -10, 20 degrees)
        for angle in [0, 12, -12, 25, -8]:
            rotated = base.rotate(angle, expand=True, resample=Image.BICUBIC)
            # clamp alpha to ICON_ALPHA
            pixels = rotated.load()
            for py in range(rotated.height):
                for px in range(rotated.width):
                    pr, pg, pb, pa = pixels[px, py]
                    if pa > 0:
                        pixels[px, py] = (pr, pg, pb, min(pa, ICON_ALPHA))
            icon_stamps.append(rotated)

    # Step 3: tile icons in brick pattern
    rng = random.Random(PATTERN_SEED)
    rows = H // GRID_STEP + 2
    cols = W // GRID_STEP + 2

    for row in range(rows):
        for col in range(cols):
            cx = col * GRID_STEP + (GRID_STEP // 2 if row % 2 else 0)
            cy = row * GRID_STEP
            # jitter
            cx += rng.randint(-6, 6)
            cy += rng.randint(-6, 6)
            stamp = rng.choice(icon_stamps)
            sx = cx - stamp.width // 2
            sy = cy - stamp.height // 2
            if sx + stamp.width > 0 and sx < W and sy + stamp.height > 0 and sy < H:
                img.alpha_composite(stamp, (sx, sy))

    # Convert to RGB for smaller file
    result = Image.new("RGB", (W, H))
    result.paste(img, (0, 0), img)
    save(result, "bg.png")


# ═══════════════════════════════════════
# 2. glass.png — golden martini glass 100x140
# ═══════════════════════════════════════
def gen_glass():
    svg = fetch_svg("martini-glass")
    img = svg_to_png(svg, 512, 512)
    img = colorize(img, ACCENT)
    img = fit_icon(img, 100, 140)
    img = flatten_alpha(img, threshold=30)
    save(img, "glass.png")


# ═══════════════════════════════════════
# 3. qr.png — golden QR frame corners 80x80
#    (no FA icon for this, keep Pillow-drawn)
# ═══════════════════════════════════════
def gen_qr():
    img = Image.new("RGBA", (80, 80), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    s = 80
    cn = s // 4
    w = 3
    for (x0, y0, x1, y1) in [
        (0, 0, cn, w - 1), (0, 0, w - 1, cn),               # top-left
        (s - cn, 0, s - 1, w - 1), (s - w, 0, s - 1, cn),   # top-right
        (0, s - w, cn, s - 1), (0, s - cn, w - 1, s - 1),   # bottom-left
        (s - cn, s - w, s - 1, s - 1), (s - w, s - cn, s - 1, s - 1),  # bottom-right
    ]:
        draw.rectangle([(x0, y0), (x1, y1)], fill=ACCENT)
    save(img, "qr.png")


# ═══════════════════════════════════════
# 4. check.png — green circle-check 100x100
# ═══════════════════════════════════════
def gen_check():
    svg = fetch_svg("circle-check")
    img = svg_to_png(svg, 200, 200)
    img = colorize(img, GREEN)
    img = fit_icon(img, 100, 100)
    img = flatten_alpha(img)
    save(img, "check.png")


# ═══════════════════════════════════════
# 5. warn.png — amber warning triangle 80x100
# ═══════════════════════════════════════
def gen_warn():
    svg = fetch_svg("triangle-exclamation")
    img = svg_to_png(svg, 200, 200)
    img = colorize(img, AMBER)
    img = fit_icon(img, 80, 100)
    img = flatten_alpha(img)
    save(img, "warn.png")


# ═══════════════════════════════════════
# 6. str0–str3.png — wine glass 48x60
#    Same FA icon, different colors per strength
# ═══════════════════════════════════════
def gen_strength_glasses():
    colors = [TEXT_SEC, GREEN, AMBER, RED]
    # str0 = empty glass, str1-3 = filled glass
    svg_empty = fetch_svg("wine-glass-empty")
    svg_full  = fetch_svg("wine-glass")

    for i, color in enumerate(colors):
        svg = svg_empty if i == 0 else svg_full
        img = svg_to_png(svg, 120, 120)
        img = colorize(img, color)
        img = fit_icon(img, 48, 60)
        img = flatten_alpha(img)
        save(img, f"str{i}.png")


# ═══════════════════════════════════════
# 7. VLW fonts — Montserrat Alternates (OFL)
# ═══════════════════════════════════════
FONT_GITHUB = "https://raw.githubusercontent.com/google/fonts/main/ofl/montserratalternates"
FONT_FILES = {
    "bold":    "MontserratAlternates-Bold.ttf",
    "regular": "MontserratAlternates-Regular.ttf",
}
FONT_CONFIGS = [
    ("mont_b28.vlw", "bold",    28),  # headings
    ("mont_b20.vlw", "bold",    20),  # subheadings
    ("mont_14.vlw",  "regular", 14),  # body text
]

_ttf_cache: dict[str, str] = {}


def fetch_ttf(style: str) -> str:
    """Download TTF from Google Fonts, cache locally."""
    if style not in _ttf_cache:
        filename = FONT_FILES[style]
        url = f"{FONT_GITHUB}/{filename}"
        print(f"  Downloading {filename} ...")
        data = urlopen(url).read()
        path = os.path.join(OUT_DIR, filename)
        with open(path, "wb") as f:
            f.write(data)
        _ttf_cache[style] = path
    return _ttf_cache[style]


def get_charset() -> list[str]:
    """ASCII printable + Cyrillic А-я + Ёё."""
    chars = [chr(c) for c in range(0x20, 0x7F)]
    chars += [chr(c) for c in range(0x0410, 0x0450)]
    chars += ["\u0401", "\u0451"]  # Ё ё
    return chars


def generate_vlw(ttf_path: str, font_size: int, chars: list[str], output_path: str):
    """Convert TTF → VLW (Processing font format for LovyanGFX)."""
    font = ImageFont.truetype(ttf_path, font_size)
    ascent, descent = font.getmetrics()

    ox, oy = font_size * 2, font_size * 2
    canvas = font_size * 6

    glyphs = []
    for char in sorted(chars, key=ord):
        code = ord(char)
        advance = int(round(font.getlength(char)))

        img = Image.new("L", (canvas, canvas), 0)
        draw = ImageDraw.Draw(img)
        draw.text((ox, oy), char, font=font, fill=255)

        bbox = img.getbbox()
        if not bbox:
            glyphs.append(dict(unicode=code, width=0, height=0,
                               xAdvance=advance, dY=0, dX=0, bitmap=b""))
            continue

        bx0, by0, bx1, by1 = bbox
        cropped = img.crop(bbox)

        glyphs.append(dict(
            unicode=code,
            width=bx1 - bx0,
            height=by1 - by0,
            xAdvance=advance,
            dY=ascent - (by0 - oy),
            dX=bx0 - ox,
            bitmap=bytes(255 if p > 100 else 0 for p in cropped.getdata()),
        ))

    with open(output_path, "wb") as f:
        w = lambda v: f.write(struct.pack(">i", int(v)))
        w(len(glyphs)); w(11); w(font_size); w(0)
        w(ascent); w(descent)
        for g in glyphs:
            w(g["unicode"]); w(g["height"]); w(g["width"])
            w(g["xAdvance"]); w(g["dY"]); w(g["dX"]); w(0)
        for g in glyphs:
            f.write(g["bitmap"])

    sz = os.path.getsize(output_path)
    name = os.path.basename(output_path)
    print(f"  {name:20s} {len(glyphs)} glyphs  {sz:>7,d} bytes")


def gen_fonts():
    chars = get_charset()
    for vlw_name, style, size in FONT_CONFIGS:
        ttf_path = fetch_ttf(style)
        generate_vlw(ttf_path, size, chars, os.path.join(OUT_DIR, vlw_name))


# ═══════════════════════════════════════
# Main
# ═══════════════════════════════════════
if __name__ == "__main__":
    print(f"Generating assets into {OUT_DIR}/\n")

    print("── Icons (Font Awesome 6 Free, CC BY 4.0) ──")
    gen_bg()
    gen_glass()
    gen_qr()
    gen_check()
    gen_warn()
    gen_strength_glasses()

    print("\n── Fonts (Montserrat Alternates, OFL) ──")
    gen_fonts()

    # Clean up downloaded TTF files (not needed on device)
    for ttf in _ttf_cache.values():
        if os.path.exists(ttf):
            os.remove(ttf)

    n_png = len([f for f in os.listdir(OUT_DIR) if f.endswith(".png")])
    n_vlw = len([f for f in os.listdir(OUT_DIR) if f.endswith(".vlw")])
    print(f"\nDone! {n_png} PNG + {n_vlw} VLW files generated.")
    print("Attribution: Icons — Font Awesome (fontawesome.com), CC BY 4.0")
    print("             Fonts — Montserrat Alternates (Google Fonts), OFL")
