[env:esp32s2]
platform = espressif32
board = lolin_s2_mini
framework = espidf
monitor_speed = 115200
board_build.flash_mode = dio
board_build.partitions = partitions.csv
board_build.filesystem = spiffs
upload_port = /dev/cu.usbmodem01
board_upload.use_1200bps_touch = yes
board_upload.wait_for_upload_port = yes
lib_deps =
    https://github.com/lovyan03/LovyanGFX.git
