#!/bin/bash
# ══════════════════════════════════════════════════════
# Theme configuration — change colors here, then run:
#   ./theme.sh
# This regenerates src/theme_colors.h and icons
# ══════════════════════════════════════════════════════

# ── Catppuccin Mocha palette ──
ACCENT="CBA6F7"    # Mauve
BG="1E1E2E"        # Base
BG_CARD="313244"   # Surface0
SURFACE1="45475A"  # Surface1
SKY="89DCEB"       # Sky
GREEN="A6E3A1"     # Green
RED="F38BA8"       # Red
PEACH="FAB387"     # Peach
YELLOW="F9E2AF"    # Yellow
TEXT="CDD6F4"      # Text
TEXT_SEC="A6ADC8"   # Subtext0
TEXT_DIM="6C7086"   # Overlay0
BORDER="45475A"    # Surface1
GRAY_BTN="181825"  # Mantle
CRUST="11111B"     # Crust

# Icon-specific
BG_ACCENT="B4BEFE" # Lavender (background pattern)
BG_TOP="1E1E2E"    # Base
BG_BOT="11111B"    # Crust

# ══════════════════════════════════════════════════════
# ── Generate src/theme_colors.h ──
# ══════════════════════════════════════════════════════

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

cat > "$SCRIPT_DIR/src/theme_colors.h" << HEADER
#pragma once
// Auto-generated by theme.sh — DO NOT EDIT MANUALLY

namespace ui {
    static constexpr uint32_t ACCENT   = 0x${ACCENT};
    static constexpr uint32_t BG       = 0x${BG};
    static constexpr uint32_t BG_CARD  = 0x${BG_CARD};
    static constexpr uint32_t SURFACE1 = 0x${SURFACE1};
    static constexpr uint32_t SKY      = 0x${SKY};
    static constexpr uint32_t GREEN    = 0x${GREEN};
    static constexpr uint32_t RED      = 0x${RED};
    static constexpr uint32_t PEACH    = 0x${PEACH};
    static constexpr uint32_t YELLOW   = 0x${YELLOW};
    static constexpr uint32_t TEXT     = 0x${TEXT};
    static constexpr uint32_t TEXT_SEC = 0x${TEXT_SEC};
    static constexpr uint32_t TEXT_DIM = 0x${TEXT_DIM};
    static constexpr uint32_t BORDER   = 0x${BORDER};
    static constexpr uint32_t GRAY_BTN = 0x${GRAY_BTN};
    static constexpr uint32_t CRUST    = 0x${CRUST};
}
HEADER

echo "Generated src/theme_colors.h"

# ══════════════════════════════════════════════════════
# ── Generate theme_colors.py (imported by generate_icons.py) ──
# ══════════════════════════════════════════════════════

hex2rgb() {
    local h="$1"
    printf "(0x${h:0:2}, 0x${h:2:2}, 0x${h:4:2})"
}

cat > "$SCRIPT_DIR/theme_colors.py" << PYFILE
# Auto-generated by theme.sh — DO NOT EDIT MANUALLY

ACCENT    = $(hex2rgb $ACCENT)
BG_ACCENT = $(hex2rgb $BG_ACCENT)
GREEN     = $(hex2rgb $GREEN)
PEACH     = $(hex2rgb $PEACH)
RED       = $(hex2rgb $RED)
TEXT_SEC  = $(hex2rgb $TEXT_SEC)
BG_TOP    = $(hex2rgb $BG_TOP)
BG_BOT    = $(hex2rgb $BG_BOT)
PYFILE

echo "Generated theme_colors.py"

# ══════════════════════════════════════════════════════
# ── Regenerate icons ──
# ══════════════════════════════════════════════════════

echo "Regenerating icons..."
cd "$SCRIPT_DIR" && python3 generate_icons.py
echo "Done!"
