#pragma once
#include <LovyanGFX.hpp>
#include "recipes.h"
#include "pumps.h"

// ── LGFX: ILI9488 + XPT2046 on ESP32-S2 Mini ──

class LGFX : public lgfx::LGFX_Device {
    lgfx::Panel_ILI9488 _panel;
    lgfx::Bus_SPI       _bus;
    lgfx::Light_PWM     _light;
    lgfx::Touch_XPT2046 _touch;

public:
    LGFX() {
        auto bcfg = _bus.config();
        bcfg.spi_host   = SPI2_HOST;
        bcfg.spi_mode   = 0;
        bcfg.freq_write  = 40000000;
        bcfg.freq_read   = 16000000;
        bcfg.spi_3wire   = true;
        bcfg.pin_mosi    = 33;
        bcfg.pin_miso    = -1;
        bcfg.pin_sclk    = 18;
        bcfg.pin_dc      = 9;
        _bus.config(bcfg);
        _panel.setBus(&_bus);

        auto pcfg = _panel.config();
        pcfg.pin_cs      = 37;
        pcfg.pin_rst     = 7;
        pcfg.panel_width  = 320;
        pcfg.panel_height = 480;
        pcfg.offset_rotation = 0;
        pcfg.readable    = false;
        _panel.config(pcfg);

        auto lcfg = _light.config();
        lcfg.pin_bl      = 35;
        lcfg.invert      = false;
        lcfg.freq        = 12000;
        lcfg.pwm_channel = 0;
        _light.config(lcfg);
        _panel.setLight(&_light);

        auto tcfg = _touch.config();
        tcfg.spi_host  = SPI2_HOST;
        tcfg.freq      = 1000000;
        tcfg.pin_cs    = 11;
        tcfg.pin_int   = 5;
        tcfg.pin_mosi  = 33;
        tcfg.pin_miso  = 16;
        tcfg.pin_sclk  = 18;
        tcfg.x_min     = 300;
        tcfg.x_max     = 3900;
        tcfg.y_min     = 300;
        tcfg.y_max     = 3900;
        _touch.config(tcfg);
        _panel.setTouch(&_touch);

        setPanel(&_panel);
    }
};

// ── Theme colors (generated by theme.sh) ──
#include "theme_colors.h"

// ── API ──

void display_init();

void display_drawIdle(int cocktailsToday);
void display_drawSelectStrength(const Recipe& recipe, const float* mults);
void display_drawDispensingStatic(const char* cocktailName);
void display_updateDispensing(float progressPct, int activePump, const char* ingredientText);
void display_drawBottleEmpty(const char* ingredientName);
void display_drawDone();

int  display_checkStrengthTap(const Recipe& recipe);
bool display_checkStopButton();
int  display_checkBottleEmptyButton();
bool display_isTouched();
bool display_checkTopTap();

extern LGFX tft;
