#pragma once
// Auto-generated by theme.sh — DO NOT EDIT MANUALLY

namespace ui {
    static constexpr uint32_t ACCENT   = 0xCBA6F7;
    static constexpr uint32_t BG       = 0x1E1E2E;
    static constexpr uint32_t BG_CARD  = 0x313244;
    static constexpr uint32_t SURFACE1 = 0x45475A;
    static constexpr uint32_t SKY      = 0x89DCEB;
    static constexpr uint32_t GREEN    = 0xA6E3A1;
    static constexpr uint32_t RED      = 0xF38BA8;
    static constexpr uint32_t PEACH    = 0xFAB387;
    static constexpr uint32_t YELLOW   = 0xF9E2AF;
    static constexpr uint32_t TEXT     = 0xCDD6F4;
    static constexpr uint32_t TEXT_SEC = 0xA6ADC8;
    static constexpr uint32_t TEXT_DIM = 0x6C7086;
    static constexpr uint32_t BORDER   = 0x45475A;
    static constexpr uint32_t GRAY_BTN = 0x181825;
    static constexpr uint32_t CRUST    = 0x11111B;
}
